Fix WikiPage::getContent argument
Prevents:
TypeError: MediaWiki\Revision\RevisionRecord::audienceCan(): Argument #2 ($audience) must be of type int, string given

ERM20742

[5.1.x]

Change-Id: I2e1116d99205a2a60c49b1d58bd610bf6bcf2a35
(cherry picked from commit 9b36b5a1f9634cd4e34903f4e8b5b82e78cb99dd)